Repository carrot-u/carrot-u-admin-app, pull requests merged in 2020-07, with the labels that each got.

#37 tinkering around with menus and mentor page
  app/assets/stylesheets/home.scss
  app/views/layouts/application.html.erb
  app/views/mentors/_form.html.erb
  app/views/mentors/new.html.erb
Labels: ruby, ui

#43 Manage waiting list
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/students_controller.rb
  app/helpers/students_helper.rb
  app/models/course_session.rb
  app/models/waiting_list.rb
  app/views/layouts/application.html.erb
  app/views/students/apply.html.erb
  app/views/students/waiting_list.html.erb
  config/routes.rb
  db/migrate/20200703142703_create_waiting_lists.rb
  db/schema.rb
  test/controllers/students_controller_test.rb
  test/fixtures/application_answers.yml
  test/fixtures/homework_submissions.yml
  test/fixtures/students.yml
  test/fixtures/users.yml
  test/fixtures/users_managers.yml
  test/fixtures/waiting_lists.yml
  test/test_helper.rb
Labels: ruby, ui

#42 application questions, mentors, users facelifts
  app/models/user.rb
  app/views/application_questions/_form.html.erb
  app/views/application_questions/edit.html.erb
  app/views/application_questions/index.html.erb
  app/views/layouts/application.html.erb
  app/views/mentors/_form.html.erb
  app/views/mentors/index.html.erb
  app/views/mentors/new.html.erb
  app/views/users/index.html.erb
Labels: ui

#46 dropping the top divider
  app/views/welcome/_carrotu_overview.html.erb
Labels: ui

#47 create mentor page was breaking for nil current user name
  app/models/user.rb
Labels: bug

#48 add spacer/fix mentor form bug
  app/views/help/index.html.erb
  app/views/mentors/_form.html.erb
Labels: bug, ui

#61 stylizing waitlist, making headers consistent H2, "Carrot U"
  app/views/course_sessions/edit.html.erb
  app/views/course_sessions/index.html.erb
  app/views/course_sessions/new.html.erb
  app/views/course_sessions/show.html.erb
  app/views/home/index.html.erb
  app/views/homework_submissions/index.html.erb
  app/views/homeworks/index.html.erb
  app/views/lectures/edit.html.erb
  app/views/lectures/index.html.erb
  app/views/lectures/new.html.erb
  app/views/lectures/show.html.erb
  app/views/mentors/edit.html.erb
  app/views/students/waiting_list.html.erb
Labels: ui

#63 update mentor signup description
  app/views/mentors/new.html.erb
Labels: ui

#64 fix mentors faq link, add margins to student signup
  app/views/mentors/new.html.erb
  app/views/students/_application.html.erb
Labels: bug, ui

#65 fix waitlist rendering
  app/views/students/waiting_list.html.erb
Labels: bug, ui

#66 student application: removing 75pct width to center better
  app/views/layouts/application.html.erb
  app/views/students/_application.html.erb
Labels: ui
